// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_S0uZC2bU-Ylq5SVggym1LtX25LzAV4M',
    appId: '1:509849159949:web:8158367c2231a03eac0844',
    messagingSenderId: '509849159949',
    projectId: 'printellect-test',
    authDomain: 'printellect-test.firebaseapp.com',
    storageBucket: 'printellect-test.firebasestorage.app',
    measurementId: 'G-ZDJHZFTYNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeK0iOID9X3NsFSgqCuE1P5tihr1e_exg',
    appId: '1:509849159949:android:e0f3ef1147bee5ecac0844',
    messagingSenderId: '509849159949',
    projectId: 'printellect-test',
    storageBucket: 'printellect-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNjW2U8kkaL0Xtxn6zKQv_tpArtO_namo',
    appId: '1:509849159949:ios:bb7f3729bb1b4033ac0844',
    messagingSenderId: '509849159949',
    projectId: 'printellect-test',
    storageBucket: 'printellect-test.firebasestorage.app',
    iosBundleId: 'com.example.printellectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNjW2U8kkaL0Xtxn6zKQv_tpArtO_namo',
    appId: '1:509849159949:ios:bb7f3729bb1b4033ac0844',
    messagingSenderId: '509849159949',
    projectId: 'printellect-test',
    storageBucket: 'printellect-test.firebasestorage.app',
    iosBundleId: 'com.example.printellectTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_S0uZC2bU-Ylq5SVggym1LtX25LzAV4M',
    appId: '1:509849159949:web:617786ca6e1c40b3ac0844',
    messagingSenderId: '509849159949',
    projectId: 'printellect-test',
    authDomain: 'printellect-test.firebaseapp.com',
    storageBucket: 'printellect-test.firebasestorage.app',
    measurementId: 'G-F0C83686XC',
  );
}
